apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skipper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/skipper.git
    targetRevision: HEAD
    path: deployment/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: skipper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
