apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-backend
  labels:
    app: skipper
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skipper
      component: backend
  template:
    metadata:
      labels:
        app: skipper
        component: backend
    spec:
      containers:
      - name: backend
        image: yourorg/skipper-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: skipper-secrets
              key: database_url
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: skipper-secrets
              key: rabbitmq_url
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: skipper-backend
spec:
  selector:
    app: skipper
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
